### ISSUE TITLE
[ERROR]: Aesthetic scorer error: local variable 'aesthetic_model' referenced before assignment

### ISSUE THREAD

**Issue by Woisek** [vladmandic/sd-extension-aesthetic-scorer#1]
Can't fix it. Also some paths appear to be wrong in the .py script (extension_path, git_home). Please check.

**Comment by vladmandic** [comment]
yes, few errors since i've moved the repo, working on it...

**Comment by vladmandic** [comment]
updated, hope it works now.

**Comment by Woisek** [comment]
Thanks, can confirm that it is now working.

Any suggestions on how we can get the score into the description after generating (the info underneath the generated image) and/or as a [tag] for using it on the filename when saved?

Currently (as far as I can see), the score is only seen if we drag the generated image into the PNG Info ... which ... is a bit tedious ... :/

**Comment by vladmandic** [comment]
modifying a filename is a no-go, but i'll look into how to add it to description.

**Comment by Woisek** [comment]
> modifying a filename is a no-go
I meant it to use in the settings of the "Images filename pattern", where we can set tags like [seed], [steps] or [sampler], if I wrote it a bit unclear.
A tag like [score] would be nice to use.

**Comment by vladmandic** [comment]
> [score] would be nice to

ahh, ok, that makes more sense - i'll look into that.

**Comment by Woisek** [comment]
Great! With that, we could then also use it to sort images after the score if this tag is at first place in the file name. :)
Thanks for your effort!

**Comment by vladmandic** [comment]
i took a look and to get access to state (from which descripton on screen is rendered), i'd have to convert the extension to an always-on/always-visible script. i'll follow-up on this and propose some imrpovements to webui so extensions have access to additional callbacks, buts its not a short term thing as those callbacks first need to be defined.

and to get access to filename template, it would be easy from main codebase itself, but there is no chance to get it from script or extension as there are no suitable callbacks at all.

anyhow, i'm closing the issue for now and will continue on dev side in the background.

**Comment by Woisek** [comment]
Thnaks for your info.
