### ISSUE TITLE
Request: Could this be adopted for ComfyUI?

### ISSUE THREAD

**Issue by tusharbhutt** [vladmandic/sd-extension-aesthetic-scorer#11]
As the title says, could this be adapted as a node for ComfyUI?  My Python skills are below non-existen but I notice you have the ability to have a CLI interface, so I thought maybe a Comfy node wouldn't be too hard to implement

**Comment by vladmandic** [comment]
Not really as it depends on webui scheduler to trigger a callback on each step.
