### ISSUE TITLE
No score output in api ?

### ISSUE THREAD

**Issue by Marcophono2** [vladmandic/sd-extension-aesthetic-scorer#14]
Hello!
Your extension works fine for me as far as I am using the Automatic 1111 webUI (Linux). But if I generate the images via api there is no score findable in the the jpg exif data or the other available parameters. Am I doing something wrong?

**Comment by vladmandic** [comment]
this extension is over a year old at this time, i really don't have time to update it - if it works, great, otherwise contributions are welcome.
