### ISSUE TITLE
Feature Request: Add scores to existing images

### ISSUE THREAD

**Issue by anonymous-person** [vladmandic/sd-extension-aesthetic-scorer#2]
Or at least document how it could be done from the CLI.

**Comment by vladmandic** [comment]
i've added cli and updated notes: <https://github.com/vladmandic/sd-extension-aesthetic-scorer#cli>

**Comment by illtellyoulater** [comment]
@vladmandic 

Why was this closed when the CLI only outputs the score to the console and does not save it within images?
How is this implementing the requested feature of _adding scores to existing images_?
Or is there something I am not getting right?

**Comment by vladmandic** [comment]
> Or at least document how it could be done from the CLI.

I've provided CLI how to get score and then its up to user to script that output to add it to image metadata. For example, using `exiftool` which is probably best metadata parser out there.

Note that option to *modify* PNGInfo/ExifInfo can be quite destructive for existing images as there is no way to add field to existing metadata. Entire metadata needs to be parsed and new metadata object created. Which means this tool would be responsible for that and I don't want to go down that path.

I can see how I would get a ticket "i previously had GPS info set, but your plugin ruined it".
