### ISSUE TITLE
Feature request: minimum aesthetic_score filter in Image Browser accepts a range

### ISSUE THREAD

**Issue by axemaster** [vladmandic/sd-extension-aesthetic-scorer#4]
Feature request: minimum aesthetic_score filter in Image Browser accepts a range

I don't know if this belong here or in the browser ext. repo. lmk if I should move it.

**Comment by vladmandic** [comment]
hate to punt on it, but its really on the image browser extension to implement filtering based on anything.
if author of that extension needs help with anything from this extension, i'm willing to help.

i suggest to create a feature request at <https://github.com/AlUlkesh/stable-diffusion-webui-images-browser>
(not the original image browser url as it seems to be abandoned and this one is well-maintained)
