### ISSUE TITLE
Why not use exif “aesthetic_score” ? (Not an issue, just a thought

### ISSUE THREAD

**Issue by ETA-22** [vladmandic/sd-extension-aesthetic-scorer#6]
Other tools/extensions seem to have seemed to standardized to using “aesthetic_score”, and not “score”, like https://github.com/AlUlkesh/stable-diffusion-webui-images-browser (The current active branch of this popular extension).

That said, maybe there’s s reason I’m not aware of for not using that exif tag. But the option would be nice, at least.

I can submit a change, but I’m not super well versed with python, and dont want to break anything.

**Comment by vladmandic** [comment]
apparently [images browser](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser) extension supports both, take a look at:

https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/blob/7e23b389eb2db5bf6d5670383598a2b3d2621184/scripts/image_browser.py#L380

if there is some issue with it, it should be reported there (and i'd be willing to work witth the author to help)

**Comment by ETA-22** [comment]
So it does! I think the only issue is documentation of that, 😂
