### ISSUE TITLE
Feature request: show score in webui

### ISSUE THREAD

**Issue by feffy380** [vladmandic/sd-extension-aesthetic-scorer#8]
Although the score is saved in the metadata, it isn't displayed in the webui, so you can't check the score right after generating the image. You currently have to read the metadata back out after the fact, which requires an extra manual step.

**Comment by vladmandic** [comment]
currently script runs via callback before image save and it only has access to image parameters - and there are no better callbacks in webui to utilize.

to achieve what you want, i'd need to convert the script to be a much more complicated post-processing type of a script (like for example codeformers). i'll consider it, but it is a low priority at the moment.

**Comment by vladmandic** [comment]
actually, i've found a way and new version is posted. i should not have closed this feature request before more consideration.
