### ISSUE TITLE
[feature request]how about try this one?

### ISSUE THREAD

**Issue by sdbds** [vladmandic/sd-extension-aesthetic-scorer#9]
https://github.com/THUDM/ImageReward

ImageReward is the first general-purpose text-to-image human preference RM, which is trained on in total 137k pairs of expert comparisons.
It outperforms existing text-image scoring methods, such as CLIP (by 38.6%), Aesthetic (by 39.6%), and BLIP (by 31.6%), in terms of understanding human preference in text-to-image synthesis. 
![702bc11c72f8b1a44371240f82818578_234455800-26d55cd9-c160-4ac0-acf3-0c993c1c4eb9](https://user-images.githubusercontent.com/8085926/235125844-6228d9aa-ba8e-42bd-bf49-f9ea290e7e2b.png)

**Comment by vladmandic** [comment]
given that prototype integation script for it already exists as written by original author <https://github.com/THUDM/ImageReward/blob/main/demo/sdwebui/image_reward.py>, this should really be made into extension of its own - if anyone is interested to create one? or ping author to create/register extension? should be quite easy given the code i've mentioned above, just needs a bit extra work, e.g. add install script that installs requirements, etc.
